---
title: "Draft Quarto document - Advanced Reproductible Research in R"
author: "María José Romero Lado"
format: html
---

```{r setup}
#| include: false
# the line below is correcting the path - as it is confusing for targets to find the quarto document inside doc folder ; it is saying go back one level and look in the _targets folder
targets::tar_config_set(store = here::here("_targets")) # here is used for relative paths
library(tidyverse)
library(targets)
library(tidymodels)

source(here::here("R/functions.R"))
# lipidomics <- read_csv(here::here("data/lipidomics.csv"))
lipidomics <- tar_read(lipidomics)
```

## Results

```{r}
tar_read(df_stats_by_metabolite) |>
  mutate(MeanSD = glue::glue("{value_mean} ({value_sd})")) |>
  select(Metabolite = metabolite, `Mean SD` = MeanSD) |>
  knitr::kable(caption = "Descriptive statistics of the metabolites.")
```

To create an interactive table you can use the DT library. See info
here: https://rstudio.github.io/DT/

```{r}
tar_read(df_stats_by_metabolite) |>
  mutate(MeanSD = glue::glue("{value_mean} ({value_sd})")) |>
  select(Metabolite = metabolite, `Mean SD` = MeanSD) |>
  DT::datatable(filter = "bottom", caption = "Descriptive statistics of the metabolites.", class = "cell-border stripe", rownames = FALSE, options = list(
    pageLength = 5, autoWidth = TRUE
  ))
```

```{r}
tar_read(fig_metabolite_distribution)
```

## Building the model

```{r}
lipidomics_wide <- lipidomics |>
  mutate(metabolite = snakecase::to_snake_case(metabolite)) |>
  metabolites_to_wider()

lipidomics_wide |>
  knitr::kable(caption = "Metabolites table - wide format.")
```

## Running multiple models

```{r}
# lipidomics |>
#     calculate_estimates() |>
#     knitr::kable(caption = "Model: T1D = metabolite + age + gender")
model_estimates <- tar_read(df_model_estimates)
```

## Visualizing the model estimates

```{r}
tar_read(fig_model_estimates)
```
